package com.collabspace.entity;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="channels",indexes={@Index(name="idx_channel_workspace",columnList="workspace_id")})
public class Channel { @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) private Workspace workspace; @Column(nullable=false,length=60) private String name; @Column(length=300) private String description; @Column(nullable=false) private boolean privateChannel=false; @ManyToOne(fetch=FetchType.LAZY,optional=false) private User createdBy; @Column(nullable=false,updatable=false) private Instant createdAt=Instant.now(); @Column(nullable=false) private Instant updatedAt=Instant.now(); @PreUpdate void touch(){updatedAt=Instant.now();} 
 public Channel() {}
 public Channel(UUID id, Workspace workspace, String name, String description, boolean privateChannel, User createdBy, Instant createdAt, Instant updatedAt) { this.id=id; this.workspace=workspace; this.name=name; this.description=description; this.privateChannel=privateChannel; this.createdBy=createdBy; this.createdAt=createdAt; this.updatedAt=updatedAt; }
public UUID getId(){return id;} public void setId(UUID v){id=v;} public Workspace getWorkspace(){return workspace;} public void setWorkspace(Workspace v){workspace=v;} public String getName(){return name;} public void setName(String v){name=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public boolean isPrivateChannel(){return privateChannel;} public void setPrivateChannel(boolean v){privateChannel=v;} public User getCreatedBy(){return createdBy;} public void setCreatedBy(User v){createdBy=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){createdAt=v;} public Instant getUpdatedAt(){return updatedAt;} public void setUpdatedAt(Instant v){updatedAt=v;}
 public static Builder builder(){return new Builder();}
 public static class Builder{ private final Channel x=new Channel(); public Builder id(UUID v){x.id=v;return this;} public Builder workspace(Workspace v){x.workspace=v;return this;} public Builder name(String v){x.name=v;return this;} public Builder description(String v){x.description=v;return this;} public Builder privateChannel(boolean v){x.privateChannel=v;return this;} public Builder createdBy(User v){x.createdBy=v;return this;} public Builder createdAt(Instant v){x.createdAt=v;return this;} public Builder updatedAt(Instant v){x.updatedAt=v;return this;} public Channel build(){return x;} }
}
