package com.collabspace.entity;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="file_attachments")
public class FileAttachment { @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) private User uploader; @ManyToOne(fetch=FetchType.LAZY) private Message message; @Column(nullable=false) private String originalName; @Column(nullable=false) private String storedName; @Column(nullable=false) private String contentType; @Column(nullable=false) private long size; @Column(nullable=false,updatable=false) private Instant createdAt=Instant.now(); 
 public FileAttachment() {}
 public FileAttachment(UUID id, User uploader, Message message, String originalName, String storedName, String contentType, long size, Instant createdAt) { this.id=id; this.uploader=uploader; this.message=message; this.originalName=originalName; this.storedName=storedName; this.contentType=contentType; this.size=size; this.createdAt=createdAt; }
public UUID getId(){return id;} public void setId(UUID v){id=v;} public User getUploader(){return uploader;} public void setUploader(User v){uploader=v;} public Message getMessage(){return message;} public void setMessage(Message v){message=v;} public String getOriginalName(){return originalName;} public void setOriginalName(String v){originalName=v;} public String getStoredName(){return storedName;} public void setStoredName(String v){storedName=v;} public String getContentType(){return contentType;} public void setContentType(String v){contentType=v;} public long getSize(){return size;} public void setSize(long v){size=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){createdAt=v;}
 public static Builder builder(){return new Builder();}
 public static class Builder{ private final FileAttachment x=new FileAttachment(); public Builder id(UUID v){x.id=v;return this;} public Builder uploader(User v){x.uploader=v;return this;} public Builder message(Message v){x.message=v;return this;} public Builder originalName(String v){x.originalName=v;return this;} public Builder storedName(String v){x.storedName=v;return this;} public Builder contentType(String v){x.contentType=v;return this;} public Builder size(long v){x.size=v;return this;} public Builder createdAt(Instant v){x.createdAt=v;return this;} public FileAttachment build(){return x;} }
}
