package com.collabspace.entity;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="messages",indexes={@Index(name="idx_msg_channel_created",columnList="channel_id,created_at"),@Index(name="idx_msg_sender",columnList="sender_id")})
public class Message { @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(fetch=FetchType.LAZY,optional=false) private Channel channel; @ManyToOne(fetch=FetchType.LAZY,optional=false) private User sender; @Column(nullable=false,length=4000) private String content; @ManyToOne(fetch=FetchType.LAZY) private Message replyTo; @Column(nullable=false,updatable=false).Default private Instant createdAt=Instant.now(); @Column(nullable=false).Default private Instant updatedAt=Instant.now(); @Column(nullable=false).Default private boolean edited=false; @Column(nullable=false).Default private boolean deleted=false; @Enumerated(EnumType.STRING) @Column(nullable=false).Default private ReadStatus readStatus=ReadStatus.SENT; @PreUpdate void touch(){updatedAt=Instant.now();} 
 public Message() {}
 public Message(UUID id, Channel channel, User sender, String content, Message replyTo, Instant createdAt, Instant updatedAt, boolean edited, boolean deleted, ReadStatus readStatus) { this.id=id; this.channel=channel; this.sender=sender; this.content=content; this.replyTo=replyTo; this.createdAt=createdAt; this.updatedAt=updatedAt; this.edited=edited; this.deleted=deleted; this.readStatus=readStatus; }
public UUID getId(){return id;} public void setId(UUID v){id=v;} public Channel getChannel(){return channel;} public void setChannel(Channel v){channel=v;} public User getSender(){return sender;} public void setSender(User v){sender=v;} public String getContent(){return content;} public void setContent(String v){content=v;} public Message getReplyTo(){return replyTo;} public void setReplyTo(Message v){replyTo=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){createdAt=v;} public Instant getUpdatedAt(){return updatedAt;} public void setUpdatedAt(Instant v){updatedAt=v;} public boolean isEdited(){return edited;} public void setEdited(boolean v){edited=v;} public boolean isDeleted(){return deleted;} public void setDeleted(boolean v){deleted=v;} public ReadStatus getReadStatus(){return readStatus;} public void setReadStatus(ReadStatus v){readStatus=v;}
 public static Builder builder(){return new Builder();}
 public static class Builder{ private final Message x=new Message(); public Builder id(UUID v){x.id=v;return this;} public Builder channel(Channel v){x.channel=v;return this;} public Builder sender(User v){x.sender=v;return this;} public Builder content(String v){x.content=v;return this;} public Builder replyTo(Message v){x.replyTo=v;return this;} public Builder createdAt(Instant v){x.createdAt=v;return this;} public Builder updatedAt(Instant v){x.updatedAt=v;return this;} public Builder edited(boolean v){x.edited=v;return this;} public Builder deleted(boolean v){x.deleted=v;return this;} public Builder readStatus(ReadStatus v){x.readStatus=v;return this;} public Message build(){return x;} }
}
