package com.collabspace.service;
import com.collabspace.dto.MessageDtos.*; import com.collabspace.entity.*; import com.collabspace.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class MessageService {private final MessageRepository messages;private final ChannelService channels;private final MessageReactionRepository reactions;private final CurrentUserService current;private final ChannelRepository channelRepo;
 public Page<MessageResponse> history(UUID channelId,int page,int size){channels.getMemberChannel(channelId);return messages.findByChannelIdAndDeletedFalseOrderByCreatedAtDesc(channelId,PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100))).map(this::dto);}
 @Transactional public MessageResponse send(UUID channelId,SendMessageRequest r){Channel c=channels.getMemberChannel(channelId);Message reply=null;if(r.replyToId()!=null){reply=messages.findById(r.replyToId()).orElseThrow(()->new NoSuchElementException("Reply target not found"));if(!reply.getChannel().getId().equals(channelId))throw new IllegalArgumentException("Reply target is from another channel");}Message m=messages.save(Message.builder().channel(c).sender(current.get()).content(r.content().trim()).replyTo(reply).build());return dto(m);}
 @Transactional public MessageResponse edit(UUID id,String content){Message m=messages.findById(id).orElseThrow(()->new NoSuchElementException("Message not found"));channels.getMemberChannel(m.getChannel().getId());if(!m.getSender().getId().equals(current.get().getId()))throw new SecurityException("You can only edit your own messages");if(content==null||content.isBlank()||content.length()>4000)throw new IllegalArgumentException("Invalid message content");m.setContent(content.trim());m.setEdited(true);return dto(m);}
 @Transactional public void delete(UUID id){Message m=messages.findById(id).orElseThrow(()->new NoSuchElementException("Message not found"));Channel c=channels.getMemberChannel(m.getChannel().getId());if(!m.getSender().getId().equals(current.get().getId()))throw new SecurityException("You can only delete your own messages");m.setDeleted(true);m.setContent("This message was deleted");}
 @Transactional public void react(UUID id,String emoji){Message m=messages.findById(id).orElseThrow();channels.getMemberChannel(m.getChannel().getId());var old=reactions.findByMessageIdAndUserIdAndEmoji(id,current.get().getId(),emoji);if(old.isPresent())reactions.delete(old.get());else reactions.save(MessageReaction.builder().message(m).user(current.get()).emoji(emoji).build());}
 public Page<MessageResponse> search(UUID workspaceId,String q,int page,int size){return messages.findByChannel_Workspace_IdAndContentContainingIgnoreCaseAndDeletedFalse(workspaceId,q,PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100))).map(this::dto);}
 public MessageResponse dto(Message m){return new MessageResponse(m.getId(),m.getChannel().getId(),m.getSender().getId(),m.getSender().getUsername(),m.isDeleted()?"This message was deleted":m.getContent(),m.getReplyTo()==null?null:m.getReplyTo().getId(),m.getCreatedAt(),m.isEdited(),m.isDeleted(),m.getReadStatus().name());}}
