package com.collabspace.service;
import com.collabspace.dto.WorkspaceDtos.*; import com.collabspace.entity.*; import com.collabspace.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class WorkspaceService {private final WorkspaceRepository workspaces;private final WorkspaceMemberRepository members;private final UserRepository users;private final CurrentUserService current;
 public List<WorkspaceResponse> list(){User u=current.get();return members.findByUserId(u.getId()).stream().map(m->toDto(m.getWorkspace())).toList();}
 @Transactional public WorkspaceResponse create(CreateWorkspaceRequest r){User u=current.get();Workspace w=workspaces.save(Workspace.builder().name(r.name().trim()).description(r.description()).owner(u).build());members.save(WorkspaceMember.builder().workspace(w).user(u).role(WorkspaceRole.OWNER).build());return toDto(w);}
 public WorkspaceResponse get(UUID id){Workspace w=workspaces.findById(id).orElseThrow(()->new NoSuchElementException("Workspace not found"));requireMember(id);return toDto(w);}
 @Transactional public WorkspaceResponse update(UUID id,UpdateWorkspaceRequest r){Workspace w=workspaces.findById(id).orElseThrow(()->new NoSuchElementException("Workspace not found"));requireAdmin(id);w.setName(r.name().trim());w.setDescription(r.description());return toDto(w);}
 @Transactional public void delete(UUID id){Workspace w=workspaces.findById(id).orElseThrow(()->new NoSuchElementException("Workspace not found"));WorkspaceMember m=member(id);if(m.getRole()!=WorkspaceRole.OWNER)throw new SecurityException("Only the owner can delete a workspace");workspaces.delete(w);}
 @Transactional public void addMember(UUID id,AddMemberRequest r){requireAdmin(id);Workspace w=workspaces.findById(id).orElseThrow();User u=users.findById(r.userId()).orElseThrow(()->new NoSuchElementException("User not found"));if(members.existsByWorkspaceIdAndUserId(id,u.getId()))throw new IllegalArgumentException("User is already a member");members.save(WorkspaceMember.builder().workspace(w).user(u).role(WorkspaceRole.MEMBER).build());}
 @Transactional public void removeMember(UUID id,UUID userId){requireAdmin(id);if(current.get().getId().equals(userId))throw new IllegalArgumentException("You cannot remove yourself");members.deleteByWorkspaceIdAndUserId(id,userId);}
 public WorkspaceMember member(UUID id){return members.findByWorkspaceIdAndUserId(id,current.get().getId()).orElseThrow(()->new SecurityException("You are not a workspace member"));}
 public void requireMember(UUID id){member(id);} public void requireAdmin(UUID id){WorkspaceRole r=member(id).getRole();if(r==WorkspaceRole.MEMBER)throw new SecurityException("Admin permission required");} public WorkspaceResponse toDto(Workspace w){return new WorkspaceResponse(w.getId(),w.getName(),w.getDescription(),w.getOwner().getId(),w.getOwner().getUsername(),w.getCreatedAt());}
}